## sep parameter

In [7]:
import pandas as pd


df=pd.read_csv('address.tsv')

In [3]:
df

  CustomerID\tName\tAge\tCity\tCountry\tPurchaseAmount
0     1001\tAlice Johnson\t28\tNew York\tUSA\t250.50
1            1002\tBob Smith\t35\tLondon\tUK\t180.75
2  1003\tCharlie Brown\t42\tSydney\tAustralia\t32...
3  1004\tDiana Lee\t31\tSingapore\tSingapore\t145.20
4     1005\tEthan Davis\t26\tToronto\tCanada\t410.90

In [5]:
df=pd.read_csv('address.tsv',sep='\t')

In [6]:
df

   CustomerID           Name  Age       City    Country  PurchaseAmount
0        1001  Alice Johnson   28   New York        USA          250.50
1        1002      Bob Smith   35     London         UK          180.75
2        1003  Charlie Brown   42     Sydney  Australia          320.00
3        1004      Diana Lee   31  Singapore  Singapore          145.20
4        1005    Ethan Davis   26    Toronto     Canada          410.90

## names parameter

In [13]:
df=pd.read_csv('address copy.tsv',sep='\t')

In [14]:
df

   1001  Alice Johnson  28   New York        USA  250.50
0  1002      Bob Smith  35     London         UK  180.75
1  1003  Charlie Brown  42     Sydney  Australia  320.00
2  1004      Diana Lee  31  Singapore  Singapore  145.20
3  1005    Ethan Davis  26    Toronto     Canada  410.90

as we can see above the column name is not given in this dataframe so we can easily give names of the column by owns

In [16]:
df=pd.read_csv('address copy.tsv',sep='\t',names=['customerid','name','age','city','country','amount'])

In [17]:
df

   customerid           name  age       city    country  amount
0        1001  Alice Johnson   28   New York        USA  250.50
1        1002      Bob Smith   35     London         UK  180.75
2        1003  Charlie Brown   42     Sydney  Australia  320.00
3        1004      Diana Lee   31  Singapore  Singapore  145.20
4        1005    Ethan Davis   26    Toronto     Canada  410.90

now we can see cleary a new row is formed of columns name

### headers parameter

whenever columns names is used as row then we use it 

syntax-pd.read_csv('test.csv',header=1)

In [3]:
import pandas as pd

### use_cols parameter

In [12]:
pd.read_csv('address.csv')

    name  age  marks
0   Ravi   21     85
1   Aman   22     90
2  Priya   20     88

In [13]:
pd.read_csv('address.csv',usecols=['name','age'])

    name  age
0   Ravi   21
1   Aman   22
2  Priya   20

 ### Squeeze parameters

it is use to make series not dataframe

In [16]:
pd.read_csv('address.csv',usecols=['name'], squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

#### in new pandas the squeeze parameter is romoved 
#### we can use modern method that is read the column and then select it

In [21]:
name=pd.read_csv('address.csv',usecols=['name'])
type(name)

pandas.DataFrame

#### here we can see it  returns a dataframe

#### now select it

In [24]:
name =pd.read_csv('address.csv',usecols=['name'])['name']

In [25]:
type(name)

pandas.Series

#### now we can see that its type change to series

  ### skiprows/nrows parameter

#### skiprows used to skip a particular rows and nrows parameter is used to print n rows this is used when data is very big so we cant load enitre data due to limited ram size

In [29]:
pd.read_csv('address.csv',nrows=2)

   name  age  marks
0  Ravi   21     85
1  Aman   22     90

### Encoding parameter

#### there are many dataset in which bydefualt encodeing is utf8 but there are some dataset which is encodeed in different format


#### lets create a df with latin1 encoding

In [35]:
df=pd.DataFrame({
    "name":["José", "André", "François", "Müller"],
    "city":["São Paulo", "Belo Horizonte", "Paris", "Berlin"]
})

df.to_csv("employee_latin1.csv", index=False,encoding="latin1")

In [36]:
pd.read_csv('employee_latin1.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte

#### as we can seee above there is an error occur due to different enoding

#### now if we know the  encoding format then we can easily load the file like

In [39]:
pd.read_csv('employee_latin1.csv',encoding='latin1')

       name            city
0      José       São Paulo
1     André  Belo Horizonte
2  François           Paris
3    Müller          Berlin

#### lets try another if dont know the encoding format 
#### we use `chardet`

In [41]:
# first isntall if chardet is not install in your venv

In [43]:
# lets try this code

try:
    df=pd.read_csv('employee_latin1.csv')
except UnicodeDecodeError:
    import chardet

    with open ('employee_latin1.csv','rb') as f:
        enc=chardet.detect(f.read())["encoding"]
    
    df=pd.read_csv('employee_latin1.csv',encoding=enc)

In [44]:
df

       name            city
0      José       São Paulo
1     André  Belo Horizonte
2  François           Paris
3    Müller          Berlin

### skip bad lines

##### when ever we got some error while  loading file like `parseError`

In [47]:
pd.read_csv('employee.csv',error_bad_lines=False)

TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'. Did you mean 'on_bad_lines'?

##### in modern pandas skip_bad_lines is replaced by `on_bad_line='skip'`

In [49]:
pd.read_csv('employee.csv',on_bad_lines='skip')

       name            city
0      José       São Paulo
1     André  Belo Horizonte
2  François           Paris
3    Müller          Berlin

In [51]:
pd.read_csv('employee_bad.csv')

ParserError: Error tokenizing data. C error: Expected 3 fields in line 4, saw 4

as we see above parse erro occured

In [53]:
pd.read_csv('employee_bad.csv',on_bad_lines='skip')

   id   name  salary
0   1   Ravi   50000
1   2   Aman   60000
2   4  Rohit   55000

it worked correctly

### dtype parameter

##### it is used when without any need in any column the bigger data type is used which causes memory loss hence we useing dtype parameter change the datatype into smalleer one like float to int

In [62]:
pd.read_csv('dataset/salary.csv')

   id   age   salary  experience
0   1  21.0  25000.0         1.0
1   2  22.0  30000.0         2.0
2   3  23.0  35000.0         3.0
3   4  24.0  40000.0         4.0
4   5  25.0  45000.0         5.0

In [65]:
pd.read_csv('dataset/salary.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5 non-null      int64
 1   age         5 non-null      float64
 2   salary      5 non-null      float64
 3   experience  5 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 292.0 bytes

here we can see that in age and experiance no need of float

In [67]:
pd.read_csv('dataset/salary.csv',dtype={'age':int,'experience':int}).info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5 non-null      int64
 1   age         5 non-null      int64
 2   salary      5 non-null      float64
 3   experience  5 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes

as we can see that dtype is changed now